version: '3.8'

services:
  website:
    image: 'lyz_web:latest'
    container_name: 'lyzsite'
    ports:
      - 1111:80
    restart: unless-stopped

networks:
  default:
    external: true
    name: lyzonenetwork